const cfg=window.ANNA_CONFIG||{};export const connected=!!(cfg.supabaseUrl&&cfg.supabaseKey);
let token=sessionStorage.getItem('anna-token')||'';
async function request(path,{method='GET',body,headers={}}={}){const r=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+path,{method,headers:{apikey:cfg.supabaseKey,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});const result=await r.text();let data;try{data=JSON.parse(result)}catch{data=result}if(!r.ok)throw new Error(data.message||data.error_description||'Не удалось выполнить запрос');return data}
export async function login(email,password){const d=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});token=d.access_token;sessionStorage.setItem('anna-token',token);try{const owners=await request('/rest/v1/site_admins?select=user_id');if(!owners.length)throw new Error('У этого аккаунта нет доступа к панели')}catch(e){logout();throw e}}
export function logout(){if(connected&&token)request('/auth/v1/logout',{method:'POST'}).catch(()=>{});token='';sessionStorage.removeItem('anna-token');sessionStorage.removeItem('anna-demo')}
export function hasSession(){return connected?!!token:sessionStorage.getItem('anna-demo')==='true'}
export async function loadContent(){if(!connected){try{return JSON.parse(localStorage.getItem('anna-content'))}catch{return null}}const d=await request('/rest/v1/site_content?id=eq.1&select=content');return d[0]?.content||null}
export async function saveContent(content){if(!connected){localStorage.setItem('anna-content',JSON.stringify(content));return}await request('/rest/v1/site_content?on_conflict=id',{method:'POST',body:{id:1,content},headers:{Prefer:'resolution=merge-duplicates'}})}
export async function bookings(){if(!connected){try{return JSON.parse(localStorage.getItem('anna-bookings')||'[]')}catch{return []}}return await request('/rest/v1/bookings?select=*&order=created_at.desc')}
export async function submitBooking(b){if(connected)return request('/rest/v1/rpc/create_booking',{method:'POST',body:{p_service:b.service,p_date:b.date,p_time:b.time,p_name:b.name,p_phone:b.phone}});const rows=await bookings();rows.unshift({...b,id:crypto.randomUUID(),status:'new',created_at:new Date().toISOString()});localStorage.setItem('anna-bookings',JSON.stringify(rows))}
export async function changeBooking(id,status,remove=false){if(connected)return request('/rest/v1/bookings?id=eq.'+encodeURIComponent(id),{method:remove?'DELETE':'PATCH',body:remove?undefined:{status}});let rows=await bookings();rows=remove?rows.filter(b=>b.id!==id):rows.map(b=>b.id===id?{...b,status}:b);localStorage.setItem('anna-bookings',JSON.stringify(rows))}
export async function available(date){if(!connected)return (await bookings()).filter(b=>b.date===date&&!['cancelled'].includes(b.status)).map(b=>b.time);return request('/rest/v1/rpc/booked_times',{method:'POST',body:{p_date:date}})}
export async function upload(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Загрузите JPG, PNG или WebP до 5 МБ');if(!connected)return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const path=crypto.randomUUID()+'.'+file.name.split('.').pop();const r=await fetch(cfg.supabaseUrl+'/storage/v1/object/site-images/'+path,{method:'POST',headers:{apikey:cfg.supabaseKey,Authorization:'Bearer '+token,'Content-Type':file.type},body:file});if(!r.ok)throw new Error('Не удалось загрузить изображение');return cfg.supabaseUrl+'/storage/v1/object/public/site-images/'+path}
