export const defaults={
brand:'Юлия masternails',hero:{eyebrow:'КРАСИВЫЕ РУКИ В ТВОЁМ РИТМЕ',title:'Твой цвет.\nТвой маникюр.',description:'Аккуратный маникюр, стойкое покрытие и забота о деталях — чтобы ты чувствовала себя уверенно каждый день.',image:'/assets/hero.jpg',script:'Больше чем просто маникюр ♡',benefits:[{icon:'heart',text:'Уютная атмосфера'},{icon:'leaf',text:'Качественные материалы'},{icon:'star',text:'Индивидуальный подход'}]},
services:[{id:'cover',name:'Маникюр с покрытием',description:'Аккуратные ногти и стойкий цвет до 3–4 недель.',price:'2 000 ₽',duration:120,image:'/assets/hero.jpg'},{id:'strength',name:'Укрепление и покрытие',description:'Для тонких и ломких ногтей. Прочность и эстетика.',price:'2 300 ₽',duration:120,image:'/assets/hearts.jpg'},{id:'design',name:'Дизайн ногтей',description:'Френч, минимализм или авторские дизайны под твой стиль.',price:'от 2 500 ₽',duration:120,image:'/assets/tiny-hearts.jpg'}],
 gallery:[{image:'/assets/burgundy.jpg',caption:'Бордовый'},{image:'/assets/hearts.jpg',caption:'Френч с сердечком'},{image:'/assets/flowers.jpg',caption:'Нежный розовый'},{image:'/assets/lines.jpg',caption:'Тонкие линии'},{image:'/assets/cherry.jpg',caption:'Спелая вишня'},{image:'/assets/tiny-hearts.jpg',caption:'Маленькая любовь'}],
 about:{eyebrow:'ДАВАЙ ЗНАКОМИТЬСЯ',title:'Привет, я Анна',text:'Для меня маникюр — это маленький ритуал заботы о себе. Люблю чистые линии, нежные оттенки и детали, которые делают образ твоим.\n\nВместе подберём форму, цвет и дизайн. А пока я работаю, ты сможешь выдохнуть и уделить время себе.',image:'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=800&q=85',certificates:[]},
contacts:{address:'Адрес студии появится здесь',phone:'',telegram:'',whatsapp:'',instagram:'',hours:'Ежедневно · 10:00–20:00'},settings:{primary:'#711A32',background:'#FBD9DF',card:'#FFF8F5',title:'Юлия masternails — маникюр и забота',description:'Аккуратный маникюр, стойкое покрытие и забота о деталях. Онлайн-запись к Анне.',keywords:'маникюр, nail artist, покрытие, дизайн ногтей',ga:'',metrika:''},
labels:{navServices:'Услуги',navWorks:'Мои работы',navAbout:'Обо мне',navContacts:'Контакты',cta:'Выбрать время',servicesTitle:'Услуги и цены',allServices:'Все услуги',worksTitle:'Мои работы',allWorks:'Смотреть все',aboutCta:'Познакомимся на маникюре',contactTitle:'Твоя пауза для себя',contactText:'Выбери удобное время — остальное я возьму на себя.',addressLabel:'СТУДИЯ',hoursLabel:'ЧАСЫ РАБОТЫ',phoneLabel:'ТЕЛЕФОН',copyright:'С заботой о твоих руках',bookingTitle:'Время для себя',bookingText:'Выбери услугу и удобное время. Я свяжусь с тобой для подтверждения.',serviceLabel:'Услуга',dateLabel:'Дата',timeLabel:'Время',nameLabel:'Твоё имя',phoneFieldLabel:'Телефон',submitLabel:'Записаться',consentLabel:'Согласна на обработку имени и телефона для записи.',successTitle:'Заявка отправлена',successText:'Анна свяжется с тобой для подтверждения времени.',closeLabel:'Хорошо',adminLink:'Кабинет мастера',telegramLabel:'Telegram',whatsappLabel:'WhatsApp',instagramLabel:'Instagram'}
};


